### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by visavi** [Gomah/insomnia-plugin-user-agents#1]
Hello, please tell me how to use this plugin,
I added it, but it doesn't substitute the random user agent

If left blank it doesn't work
only if you fill out the field yourself

![image](https://github.com/Gomah/insomnia-plugin-user-agents/assets/826831/eb7e6856-1c92-49ea-b9ac-97a9eeae1017)

Insomnia 9.3.1

**Comment by Gomah** [comment]
Hey @visavi,

Have you tried to look up the value with ctrl + space?

<img width="663" alt="Screenshot 2024-07-04 at 11 15 40 am" src="https://github.com/Gomah/insomnia-plugin-user-agents/assets/2362138/b8625c03-5d56-40d3-bf02-4d76765a9480">

**Comment by visavi** [comment]
Thanks, it works, great plugin
